# -*- coding: utf-8 -*-
"""students(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L5ct7YkJJ6HMik7LuDCQEDM1az2PxMdl
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("StudentsPerformance_preprocessed.csv")

df["average score"] = (
    df["math score"] +
    df["reading score"] +
    df["writing score"]
) / 3

sns.barplot(
    data=df,
    x="parental level of education",
    y="average score",
    hue="lunch"
)

plt.title("Average Score by Parental Education and Lunch Type")
plt.xticks(rotation=45)
plt.show()

sns.boxplot(
    data=df,
    x="test preparation course",
    y="average score"
)

plt.title("Score Variance Based on Test Preparation")
plt.xlabel("Test Preparation Course")
plt.ylabel("Average Score")
plt.show()

sns.pairplot(
    df,
    vars=["math score", "reading score", "writing score"]
)

plt.show()

scores = df[
    ["math score", "reading score", "writing score"]
]

corr = scores.corr()

sns.heatmap(
    corr,
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)

plt.title("Correlation Between Math, Reading and Writing Scores")
plt.show()

print(df.groupby("parental level of education")[
    ["math score", "reading score", "writing score"]
].mean())


print(df.groupby("lunch")[
    ["math score", "reading score", "writing score"]
].mean())


print(df.groupby("test preparation course")[
    ["math score", "reading score", "writing score"]
].mean())