# -*- coding: utf-8 -*-
"""Healthcare.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NCl1LmxNJsTBjJNcFrjmjRzawoZdfH3L
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("healthcare_dataset.csv")

df.head()

df.tail

df.columns

df.dtypes

df.shape

df.isnull().sum()

df["Medical_Code"].isnull().sum()

df["Medical_Code"]=df["Medical_Code"].fillna('Unknown')

df['Discharge_Date']=pd.to_datetime(df['Discharge_Date'])
df['Discharge_Date']

df['Admission_Date']=pd.to_datetime(df['Admission_Date'])
df['Admission_Date']

df['Admission_Type']

df["Admission_Type"]=(
    df["Admission_Type"]
    .str.strip()
    .str.lower()
)

df["Admission_Type"].value_counts()

df["Billing_Amount"].describe()

df["Hospital_Stay_Days"]=(df["Discharge_Date"]-df["Admission_Date"]).dt.days
df["Hospital_Stay_Days"].head()

df["Billing_Amount"]

df["Hospital_Stay_Days"].describe()

pd.crosstab(df["Medical_Condition"],df["Gender"])