# -*- coding: utf-8 -*-
"""Healthcare-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xwH6HElK2GVmFEhEqSMcLmkUxn5_jefO
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("healthcare_dataset (1).csv")

df.head()

df.isnull().sum()

df['Date of Admission'] = pd.to_datetime(df['Date of Admission'])
df['Discharge Date'] = pd.to_datetime(df['Discharge Date'])

df['No_of_days_stayed'] = (df['Discharge Date'] - df['Date of Admission']).dt.days

df["No_of_days_stayed"].head()

billing = df.groupby('Admission Type')['Billing Amount'].sum()

billing.plot(
    kind="bar",
    figsize=(10,6),
    stacked=True
)
plt.title("Billing Amount by Admission Type")
plt.xlabel("Admission Type")
plt.ylabel("Billing Amount")
plt.show()

plt.figure(figsize=(10,6))
sns.violinplot(
    data=df,
    x="Admission Type",
    y="No_of_days_stayed"
)
plt.title("Number of days stayed by Admission Type")
plt.xlabel("Admission Type")
plt.ylabel("Number of Days Stayed")
plt.show()

df['Admission Month'] = df['Date of Admission'].dt.month
df['Admission Month']

monthly_admissions = df.groupby('Admission Month').size()
monthly_admissions

plt.figure(figsize=(12,6))
monthly_admissions.plot(
    kind="line", marker="o"
)
plt.title("Monthly patient Admissions")
plt.xlabel("Month")
plt.ylabel("Number of Admissions")
plt.xticks(rotation=45)
plt.grid()

correlation_matrix = df[["Age","No_of_days_stayed", "Billing Amount"]].corr()
correlation_matrix

sns.heatmap(correlation_matrix,annot=True,cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()

