# -*- coding: utf-8 -*-
"""Students.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xfS0scKjHnezmklfJ0KeFRidxmY4CfbM
"""

import pandas as pd
import numpy as np

df = pd.read_csv('StudentsPerformance.csv')

df.head()

columns = ['gender', 'race/ethnicity', 'parental level of education',
           'lunch', 'test preparation course']

for col in columns:
    df[col] = df[col].str.strip().str.lower()
df[columns].head()

scores = ['math score', 'reading score', 'writing score']

for col in scores:
    print(col, "Mean =", df[col].mean())

for col in scores:
    print(col, "Median =", df[col].median())

for col in scores:
    print(col, "Standard Deviation =", df[col].std())

for col in scores:
    print(col)
    print("Q1 =", df[col].quantile(0.25))
    print("Q2 =", df[col].quantile(0.50))
    print("Q3 =", df[col].quantile(0.75))