# -*- coding: utf-8 -*-
"""Apple stock.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SBw2PQCW6mBuc2Jg5c61Sh6a1Pv6IpDS
"""

import pandas as pd

data = pd.read_csv("AAPL.csv")

print("Dataset loaded successfully")

data.head()

data["Daily Delta"] = data["Close"] - data["Open"]

data.head()

top_10 = data[data["Daily Delta"] > 0].sort_values("Daily Delta", ascending=False).head(10)

print(top_10[["Date", "Open", "Close", "Daily Delta"]])

data["Daily Return"] = ((data["Close"] - data["Open"]) / data["Open"]) * 100

data.head()

top_10_returns = data.sort_values("Daily Return", ascending=False).head(10)

print(top_10_returns[["Date", "Open", "Close", "Daily Return"]])