# -*- coding: utf-8 -*-
"""Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Db265EE022XuEGKjzV04LgfHjll9T1rG
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("AAPL.csv")
df["Date"] = pd.to_datetime(df["Date"])

df

df.head()

plt.figure(figsize=(16, 8))
plt.plot(df.index, df["Open"], label="Open")
plt.plot(df.index, df["High"], label="High")
plt.plot(df.index, df["Low"], label="Low")
plt.plot(df.index, df["Close"], label="Close")
plt.title("AAPL Stock OHLC Prices")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(14,6))
plt.plot(df["Date"],df["Volume"])
plt.title("AAPL Trading Volume")
plt.xlabel("Date")
plt.ylabel("Volume")
plt.show()

df["MA20"] = df["Close"].rolling(20).mean()
df["MA50"] = df["Close"].rolling(50).mean()
plt.figure(figsize=(16, 8))
plt.plot(df["Date"], df["Close"], label="Close")
plt.plot(df["Date"], df["MA20"], label="20-Day Moving Average")
plt.plot(df["Date"], df["MA50"], label="50-Day Moving Average")
plt.title("AAPL Closing Price with Moving Averages")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.xticks(rotation=45)
plt.show()